### ISSUE TITLE
Wrong file name?

### ISSUE THREAD

**Issue by carlosen14** [FarmBot/mqtt-gateway#4]
Step 5 says..  
> WEB_API_URL=http://localhost:3000 node app/index.js. See note below*.

but inside app folder, index.js doesn't exists, is named index.ts

**Comment by RickCarlino** [comment]
Whoops! That is indeed a typo. Thanks for bringing it to our attention. Try this instead:

```
WEB_API_URL=http://localhost:3000 node app/index.js
```

I have updated the documentation accordingly.
