### ISSUE TITLE
MQTT log in

### ISSUE THREAD

**Issue by Klimbim1** [FarmBot/mqtt-gateway#7]
Trying to connect to the MQTT via MQTT.fx, I wonder where I can get this one from:

 A JSON Web Token from the API can be used as a password.

Any explanation?

Thanks, Best
Klim

**Comment by RickCarlino** [comment]
Please see this section of the documentation: ["Q: How Can I Generate an API Token"](https://github.com/RickCarlino/farmbot-web-app#q-how-can-i-generate-an-api-token). You will probably want to use the `curl` method.
