### ISSUE TITLE
The pi3 cloud not connect

### ISSUE THREAD

**Issue by Arduns** [FarmBot/mqtt-gateway#9]
AUTH START
Will fetch certificate...
Did fetch certificate. Will verify token with certificate.
AUTH FAIL androidsk@gmail.com
jwt malformed
{ Error
    at Object.module.exports [as verify] (/home/ardun/mqtt/node_modules/jsonwebtoken/verify.js:54:17)
    at ok (/home/ardun/mqtt/app/security/verify_token.js:24:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7) name: 'JsonWebTokenError', message: 'jwt malformed' }
－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
and pi3 ：Could not log in to web application. This is probably due to a bad username or password.

http://192.168.1.215:8080/app/device

**Comment by RickCarlino** [comment]
Hi @Arduns , sorry for the slow response these days (I saw you posted a few things on the forum- it's been a busy week).

You are most likely getting this error because you entered a bad password when logging in.

 * How recent is your current local setup? Please type `git log -1` within the webapp and MQTT directory.
 * Have you modified the software in any way?
 * How did you get this message? Did you log in via the web app? Or were you performing application development on a custom FarmBot software package?

**Comment by Arduns** [comment]
@RickCarlino 

1、
ardun@ubuntu:~/Farmbot-Web-App$ git log -1

commit 9a08440b0d832cb95692acc2fe0f068342eef324
Author: Rick Carlino <rick.carlino@gmail.com>

ardun@ubuntu:~/mqtt$ git log -1

commit 51172aec4be834df3d1c01feec08d1ff8200464e
Author: Rick Carlino <rick.carlino@gmail.com>

2、
i did not  modified the software 

3、
     1） I can login ！ 
     2） this error is when I use MQTT try to connect it！
     3）No！ the clients  is connected  


=== Incoming Message ===
$SYS/ryVpCoo4-/new/clients
mqttjs_28216f42
clientDisconnected

=== Incoming Message ===
$SYS/ryVpCoo4-/disconnect/clients
mqttjs_28216f42
AUTH START
Will fetch certificate...
Did fetch certificate. Will verify token with certificate.
AUTH OK device_157
clientConnected

![wechatimg14377](https://user-images.githubusercontent.com/10508878/27919712-f958a7f2-62a4-11e7-9ef5-9b30f57180be.jpeg)

**Comment by RickCarlino** [comment]
@Arduns Canyou send a screen shot of your javascript console? (`ctrl` + `shift` + `J`)

**Comment by Arduns** [comment]
@RickCarlino 
 client
![wechatimg14438](https://user-images.githubusercontent.com/10508878/27940662-81f9a288-62fe-11e7-8e2e-40a46490c89b.jpeg)
Log
![wechatimg14439](https://user-images.githubusercontent.com/10508878/27940663-81f9d352-62fe-11e7-80ed-c12c5a7d3bb3.jpeg)
driver
![wechatimg14444](https://user-images.githubusercontent.com/10508878/27940767-568f1960-62ff-11e7-866e-305d84d4fdaf.jpeg)

**Comment by Arduns** [comment]
Maybe it's just listen on IPv6 does not listen on IPv4 ！ 
ardun@ubuntu:~/Farmbot-Web-App/src/api$ netstat -nlp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 192.168.1.215:8080      0.0.0.0:*               LISTEN      2497/node       
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp        0      0 192.168.1.215:3000      0.0.0.0:*               LISTEN      2480/ruby       
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      -               
tcp6       0      0 :::3002                 :::*                    LISTEN      2765/node       
tcp6       0      0 :::1883                 :::*                    LISTEN      2765/node       
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -               
udp        0      0 0.0.0.0:29057           0.0.0.0:*                           -               
udp6       0      0 :::60283                :::*                                -               
Active UNIX domain sockets (only servers)

**Comment by RickCarlino** [comment]
@Arduns I just noticed that your password is only a few characters long in MQTTFx.

You can't use the web app password as an MQTT password. You must use your API token.

It will look something like this:

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE0OTk2OTA3MjQsImp0aSI6IjhkYWIwODc4LWRiYmYtNDljMC04MDY5LTBhY2YzYWNmOGFmYiIsImlzcyI6Ii8vbG9jYWxob3N0OjMwMDA....wqGcXiXuNqdQ4xPzfE1gpaGyZYaUsPZyv6QrjtYhiMQ-4mqD_kXQg099CnJq_lZp0Z8UZhg8eXrJx1puApJRBtxVD3aJgZI2sFQSHxB3Q
```

You can get an API token via the API.  Typing `store.getState().auth.token.encoded` from the javascript console of the web app will show the current API token for your account (you must be logged in to do this).

**Comment by Arduns** [comment]
@RickCarlino  i have get token,and login with MQTTFx! i have another question why i cant not login when used pi3

**Comment by RickCarlino** [comment]
@Arduns Do you have any logs from the bot available when this happens? You will need an [FTDI cable](https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20170710084045&SearchText=FTDI+Cable) to view the logs, but it is very helpful for seeing errors from Farmbot OS.

**Comment by Arduns** [comment]
@RickCarlino  i see the log  but it's show any errors just time is error 
the log is when i click the submit buttom
![image](https://user-images.githubusercontent.com/10508878/28031124-e67af8ec-65d8-11e7-9994-1744fac33ee9.png)

**Comment by RickCarlino** [comment]
@Arduns It looks like Farmbot can't connect to `http://192.168.1.215:80`.

Are you able to reach http://192.168.1.215:80 from a computer on the network. Be sure to try it on a completely different machine and not from the same device running the server.

Also, which command did you use to start the server? Did you use `rails s -b 0.0.0.0`? This may be an issue with the documentation. Thanks for letting us know.

**Comment by Arduns** [comment]
@RickCarlino  
i use
sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
but it did not work！
i use a ubuntu14.04 server and i debug on may macbook use ssh!

Farmbot_app and mqtt is start use " npm run dev"  with the documentation ！

I have to use rails s -b 0.0.0.0  to start the Farmbot_app and  start the web app in npm start ?

**Comment by RickCarlino** [comment]
Try this (just for now):

```
./install_frontend.sh
rails s -b 0.0.0.0 --port=80
```

This may be a bug with the documentation that we need to update. Pleae let me know if that fixes the issue and I can update the docs.

**Comment by Arduns** [comment]
the log looks like alway the server  is "https://my.farmbot.io" not my server 

Last message: :try_log_in
State: %{broadcast: false, context: #Context<0.0.1.1684>, interim: {"androidsk@gmail.com", "qazxsw", "http://192.168.1.215"}, secret: nil, server: "https://my.farmbot.io", sub: #PID<0.246.0>, timer: #Reference<0.0.1.2152>, token: nil}

**Comment by Arduns** [comment]
@RickCarlino ./install_frontend.sh
rails s -b 0.0.0.0 --port=80  it is work can start the web app but the api is not start and then mqtt not work！

**Comment by Arduns** [comment]
@RickCarlino  just make the api use the port 80 and web app use 8080 ！it work！ thanks for help！
![image](https://user-images.githubusercontent.com/10508878/28070141-7f3c1b06-667e-11e7-9624-be45281c9da0.png)

**Comment by RickCarlino** [comment]
@Arduns Great! Glad it works now. I will close the issue.
